version: 2.1
orbs: 
  node: circleci/node@5.0.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run unit tests
workflows:
  test_solutions:
    jobs:
      - test
